### ISSUE TITLE
Figma new link is not working anymore

### ISSUE THREAD

**Issue by MChrys** [storybookjs/addon-designs#244] opened 2024-06-23 12:32 UTC
### Affected design types

- [X] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

my old component link from figma is still working but now, I tried to update link (add new also in new stoy)
now this is what I get in my story book 
<img width="1154" alt="image" src="https://github.com/storybookjs/addon-designs/assets/18635108/001c4133-bc77-4307-b45d-a29db6049291">
I'm still using the same browser (chrome)
what is weird is my old link still loading properly but is I'm copy paste the updated link of the same component it is not working .

### How to reproduce the bug?

go in figma and get a new link with cmd + L or right click copy and copy link to selection 

add it in your story like that : 
```
export const Default: Story = {
  parameters: {
    design: {
      type: 'figma',
      url: 'https://www.figma.com/design/t8x8Z4dRrFG5WjZ2WWVisd/space?node-id=687-19311&t=p3wjagyQydsnxEu0-4',
    },
  },
  args: {},
};
```
and save and check in your storybook the figma tab in the related story 

### Expected behaviour

I expected the figma view load properly like before

### Environment

- [X] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

lastest

### Storybook versions

lastest

**Comment by CollinHerber** [comment] 2024-06-25 12:55
Getting this as well with 
```
Refused to frame 'https://www.figma.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' vscode-webview: vscode-file:".
```

Logged in the console

**Comment by CollinHerber** [comment] 2024-06-25 13:05
Looks like it may be related to https://github.com/storybookjs/addon-designs/pull/240/files

**Comment by MChrys** [comment] 2024-06-25 13:14
how would you explain that the old link of the same component is still working ?

**Comment by pocka** [comment] 2024-06-26 11:21
Duplicate of #239

**Closed by pocka** 2024-06-26 11:21 UTC
Labels: category: bug
