### ISSUE TITLE
Latest version(s) aren't being published

### ISSUE THREAD

**Issue by livzr** [storybookjs/addon-designs#208] opened 2023-08-11 09:51 UTC
### Affected design types

- [ ] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

The latest versions for major version 7 aren't being published and so the package can't be upgraded to meet the requirements of storybookv7. The latest published version is `[7.0.0-beta.1](https://www.npmjs.com/package/storybook-addon-designs/v/7.0.0-beta.1)`.

### How to reproduce the bug?

N/A

### Expected behaviour

Package version number should be bumped to publish correct version.

### Environment

- [ ] Chrome / Chromium / Chromium based browsers
- [ ] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

v7 onwards

### Storybook versions

v7 onwards

**Comment by pocka** [comment] 2023-08-11 09:54
Duplicate of #199 (#200)

**Closed by pocka** 2023-08-11 09:54 UTC
Labels: close: duplicate, close: invalid
