### ISSUE TITLE
storybook 7. 0.12 not working with storybook-addon-designs@6.3.1

### ISSUE THREAD

**Issue by immanual-tsw** [storybookjs/addon-designs#194] opened 2023-05-19 13:15 UTC
When I try to run the storybook, it is showing that - 
" Attention: We've detected that you're using the following addons in versions which are known to be incompatible with Storybook 7:
- storybook-addon-designs@6.3.1"

I was unable to give previous versions of SB to try if this works with that. 

Please help me out.

Thank you!

**Comment by mtirimie1** [comment] 2023-06-09 20:07
Is there any update on whether or not this will get updated? This is currently my only package with a conflict

**Comment by pocka** [comment] 2023-06-10 23:34
Duplicate of #191.

**Closed by pocka** 2023-06-10 23:34 UTC
Labels: close: duplicate
