### ISSUE TITLE
Version 7.0.0 not available on npmjs

### ISSUE THREAD

**Issue by ghost** [storybookjs/addon-designs#203] opened 2023-08-03 13:21 UTC
### Affected design types

- [ ] figma
- [ ] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

The version 7.0.0 is not available on npmjs.com last version being [7.0.0-beta.1](https://www.npmjs.com/package/storybook-addon-designs/v/7.0.0-beta.1)

### How to reproduce the bug?

/

### Expected behaviour

Latest released version should be published to npmjs.com

### Environment

- [X] Chrome / Chromium / Chromium based browsers
- [X] Firefox
- [X] macOS Safari
- [X] iOS Safari
- [X] Samsung Internet
- [X] Other

### Affected versions

7.0.0

### Storybook versions

7.1.0

**Comment by pocka** [comment] 2023-08-03 15:16
Duplicate of #200

**Closed as not planned by pocka** 2023-08-03 15:16 UTC
Labels: close: duplicate, close: invalid
